### ISSUE TITLE
Adding food for previous days

### ISSUE THREAD

**Issue by georgia-ga** [digitalnomadacademy/meal_tracker#2]
I was expecting to be able to select a day in the past and add my food for that day. But actually I am not allowed to click on a day from the past.

**Comment by SempaiEcchi** [comment]
![image](https://user-images.githubusercontent.com/16268333/84571946-160f7480-ad97-11ea-93a5-4bffac872ff6.png)
would it be okay if a tap on one of these days brings up the popup you usually get on floating action button?

**Comment by georgia-ga** [comment]
yeah

**Comment by matejthetree** [comment]
Sure.
