### ISSUE TITLE
Can't delete an option?

### ISSUE THREAD

**Issue by georgia-ga** [digitalnomadacademy/meal_tracker#3]
I've clicked on snack and chosen a meal type, but then I realised I didn't have a snack.
I can change the meal type but I can't click do delete it?
Clicking on the snack in the middle should reset it I think.

**Comment by SempaiEcchi** [comment]
![image](https://user-images.githubusercontent.com/16268333/84571936-fa0bd300-ad96-11ea-8534-7fff1de571fe.png)
long press on red meat would bring up this popup
