### ISSUE TITLE
email addresses

### ISSUE THREAD

**Issue by georgia-ga** [digitalnomadacademy/meal_tracker#7]
My friend was able to register with @gnail.com
Is there a way we can check emails are correct when a user signs up?
Or perhaps just give them a prompt to double-check the address is correct?
If not it's ok, I don' think it's a massive deal as a user can always edit that in their settings

**Comment by SempaiEcchi** [comment]
I added a text field in which the user has to reenter the address, is that okay?

**Comment by matejthetree** [comment]
No,

Either we add email confirmation or we leave it as it is.

Before adding a solution, make a proposal first :)
